language: rust
matrix:
  include:
    - rust: stable
    - os: osx

    - env: LIBZ_SYS_STATIC=1
    - env: LIBZ_SYS_STATIC=1
      os: osx

    - rust: stable
      script:
        - cargo generate-lockfile
        - ci/run-docker.sh

    - rust: beta
    - rust: nightly

    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master
script:
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml
notifications:
  email:
    on_success: never
