[package]

name = "libz-sys"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "z"
build = "src/build.rs"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/libz-sys"
description = """
Bindings to the system libz library (also known as zlib).
"""

[build-dependencies.pkg-config]
git = "https://github.com/alexcrichton/pkg-config-rs"
version = "0.1.0"
